### ISSUE TITLE
Investigate controller update method for production units

### ISSUE THREAD

**Issue by asmodai27** [RespiraWorks/Ventilator#1072]
**What has to be done**
Something to think about when doing embedded software is how do we deploy a new firmware version to a production unit.
The use of a debugger like the ST-Link we have on the nucleo board and we use for development is overkill and has the potential to create a security risk (it allows access in debug mode to a running unit).
What most embedded software manufacturers do is have a "download" mode in their firmware (triggered from a specific command or boot sequence) which allows uploading the new firmware version using the operational link (in our case, the serial link to the Pi).

**Subtasks:**
* [ ] Evaluate the potential for security risk from using a debugger in the case of an open source project (in my experience, the reason manufacturers frown upon the debugger solution is the potential to download and then study the firmware)
* [ ] Evaluate the possibility to do this from the Pi that is inside the unit and secure that function from the Pi.
* [ ] Identify other potential methods like the use of a specific sequence to update from the operational link to the Pi.
* [ ] Decide on a solution an implement it

**How do you know it has to be done**
Personal experience + comments on provision in debug library

**Starting points**
See subtasks

**Don't forget**
- [ ] Put the issue in a milestone
- [ ] Assign it to one of the projects
- [ ] Add appropriate labels
- [ ] Mention dependent/blocked issues if any
