### ISSUE TITLE
Add support for requirements traceability

### ISSUE THREAD

**Issue by dheater** [RespiraWorks/Ventilator#1078]
We created a Sphinx-based example for documenting requirements. However, it does not support requirements traceability (very well) or checking for uniqueness of requirement ids.

**What is required**
Extend the Sphinx-based requirement generation to include assistance for linking requirements.

**Subtasks:**
* [x] Install [sphinxcontrib-traceability](https://pypi.org/project/sphinxcontrib-traceability/) module
* [x] Generate example requirements traceability
* [x] Document linking process

**How do you know it has to be done**

Requirements traceability is a key part of IEC 62304 compliance

**Starting points**
https://pypi.org/project/sphinxcontrib-traceability/

**Don't forget**
- [x] Put the issue in a milestone
- [x] Assign it to one of the projects
- [x] Add appropriate labels
- [x] Mention dependent/blocked issues if any

Related issue: #1022 
Blocks: #803

**Comment by dheater** [comment]
Done
