### ISSUE TITLE
Pull requirement comments from Valispace

### ISSUE THREAD

**Issue by dheater** [RespiraWorks/Ventilator#1088]
**What has to be done**

There are comments on requirements in Valispace that should be reviewed and migrated as appropriate.  Some are rationale for requirements. Others are questions or change requests that should probably be PRs against the requirement.

**Subtasks:**
* [-] Add subtasks or sections of content if applicable
* [-] Identify documentation that should be updated upon completion

**How do you know it has to be done**

We don't want to loose this information

**Starting points**

Go to Valispace and review the comments. Disposition according to their content.

**Don't forget**
- [x] Put the issue in a milestone
- [x] Assign it to one of the projects
- [x] Add appropriate labels
- [x] Mention dependent/blocked issues if any

Relates to issue #803

**Comment by dheater** [comment]
Done
