### ISSUE TITLE
Air intakes on bottom of enclosure

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#1098]
**What is required**
We need cutouts for air intake on the bottom panel of the enclosure.
We probably want 2 of these.

**Subtasks:**
* [ ] Cutouts for air intake
* [ ] Selection of possible air filters - low profile preferred so as to not require taller feet
* [ ] Mounting points for possible air filters

**How do you know it has to be done**
Need to have airflow past the stepper motors, because they are likely to emit a lot of heat.

**Starting points**
Cutouts should go under the front quadrants of the equipment tray frame, because the back quadrants are likely to be occupied by battery and blower and other equipment that would interfere with potential air filter we might want to install.

**Don't forget**
- [x] Put the issue in a milestone
- [x] Assign it to one of the projects
- [x] Add appropriate labels
- [x] Mention dependent/blocked issues if any

**Comment by inceptionev** [comment]
Notes from meeting:

- Intake should be filtered to prevent dust buildup
- Could use the same filter as the side fan openings, however these are 9mm tall, so they will either drive the need for tall feet on the bottom of the enclosure or they will have to be mounted on the inside of the enclosure.
- Filter can be inside or outside the enclosure, but outside is preferred for serviceability
- If a low profile filter is available, this would be good because it lessens the requirement for tall feet to provide a bottom gap beneath the ventilator.
- If possible, a snap in filter is good because it eliminates fasteners.

**Comment by martukas** [comment]
Completed in 1117
