### ISSUE TITLE
Update drawing templates

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#1100]
STUB_OUT

Please take the time to describe the issue in detail, so that other contributors can pick it up and implement or declare it done/obsolete in case if was completed out of band.

**A TASK** is something that may not add functionality to the product but entails research, analysis, investigation, testing or manufacture of components or prototypes.

**What has to be done**
Describe what has to be done, ideally in declarative form - what does success look like.

**Subtasks:**
* [ ] Add subtasks or sections of content if applicable
* [ ] Identify documentation that should be updated upon completion

**How do you know it has to be done**
Link any documents, Slack threads, quote personal communication, reference your personal domain expertise etc. explaining why you think this should be done.

Link to requirements or risk analysis if applicable.

**Starting points**
Where might one start with solving this problem? Point to any relevant files or websites. Even if you have but a vague idea, please share. Perhaps something has prevented you or blocked you from solving the problem already?

**Don't forget**
- [ ] Put the issue in a milestone
- [ ] Assign it to one of the projects
- [ ] Add appropriate labels
- [ ] Mention dependent/blocked issues if any

**Comment by martukas** [comment]
From discussions with @gokcemay, we have concluded that the ISO standard is the way to go. DIN is the old German standard that is mostly superseded by ISO.
