### ISSUE TITLE
Controller code should be aware of its own version

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#1132]
**What is required**
Controller code should compile in such a way that it is aware of its own version - i.e. the build script should somehow hard-code the commit hash and clean/dirty flag into the controller code. This information should then be available for query via the debug interface.

**Subtasks:**
* [ ] scripts that query git for version and clean/dirty status, generate necessary code and ensure that it links when building controller
* [ ] Create hooks in the debug interface that allow user to query these (immutable) values

**How do you know it has to be done**
Right now, `TestData` saves the current git information from the machine that is running the Python code, but there is no guarantee of what version of code was used to generate the controller code. This makes the provenance of test data ambiguous. Furthermore, when deployed in production, it should be possible to ensure the compatibility of GUI and controller code.

**Starting points**
Experience with implementing similar version self-awareness in other C++ projects indicates that the best way to do this is likely as follows:
* have a bash script generate a header file with macro definitions containing the relevant git data
* have this generated file be explicitly ignored by git, because we want it changing with every build
* it is also possible to add any other data about the machine on which this code is being built, date and time of build, user, etc..
* there can then be additional permanent code that makes use of those macro definitions and wraps them into strong types and exposes them to the rest of the program
* have the bulid system (in this case platformio) include the generated header if necessary. Running the build in the context of the relevant scripts should endure that the file is available.

**Don't forget**
- [x] Put the issue in a milestone
- [x] Assign it to one of the projects
- [x] Add appropriate labels
- [ ] Mention dependent/blocked issues if any
