### ISSUE TITLE
Using a requirements.txt and venv to automate Python Package Installation

### ISSUE THREAD

**Issue by a-vinod** [RespiraWorks/Ventilator#1133]
Right now, we have to `pip install <pkg>` each of the packages required for the Python debugging interface. This on its own isn't a huge deal, but as time goes on, the functions we use from packages here may become deprecated or change. 

**What is required**
A quick way to address this is by creating a `requirements.txt` in `software/utils/` that has the necessary packages and the versions used at the time of development. And by using a virtual environment, we can eliminate conflicts with packages on the host machine.

**Subtasks:**
* [ ] Identify necessary packages and their versions
* [ ] Put them in requirements.txt
* [ ] Edit `controller_debug.sh` to create a venv and install the packages via rqmts.txt on its first run and use it on subsequent runs

**How do you know it has to be done**
The requirements.txt is used to both automate Python package installation and keep track of versions. This is important because developers should be on the same versions so that their dependencies are as close to each others' as possible.

**Starting points**
- Create a fresh venv
- Try running the `debug_cli.py` script manually 
- Test each function in the debugging interface
- If Python gives a `ModuleNotFoundError`, install it manually and add it to the requirements.txt
- Add steps to the controller_debug.sh script to create a venv with the dependencies in requirements.txt if it doesn't exist or use one if it exists.
