### ISSUE TITLE
Implement explicit registry for debug variables

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#1148]
**What is required**
There should be an explicit registry for tracking debug variables. It should be implemented as a proper singleton pattern and will be responsible for managing debug variables and providing access to them for the debug interface handlers.

**Subtasks:**
* [ ] Create a debug variable registry as a singleton
* [ ] Ensure that variables are registered as unique, even as class members
* [ ] Create some sort of contingency for variable ID clashes and other errors related to debug variable management
* [ ] Ensure that the debug variable classes have minimal dependencies, disentangling their implementation from that of anything else in the HAL or the rest of the debug interface

**How do you know it has to be done**
Current implementation is very naive -- a static global array and counter. No error checking is performed for name clashes. No facilities are provided for using debug variables as class members.

**Starting points**
A pattern for implementing a singleton has been mentioned in review for #1063 
The registry should ultimately issue unique IDs, but it may be possible to allow classes to negotiate this naming. It may be useful to have the registry provide functions that answer questions such as "does a variable with this ID already exist?" It may also be desirable to have debug variable initialization be separate from getting them registered. This would allow classes to dynamically register these variables based on some more complex logic.

**Don't forget**
- [x] Put the issue in a milestone
- [x] Assign it to one of the projects
- [x] Add appropriate labels
- [x] Mention dependent/blocked issues if any
