### ISSUE TITLE
Automate exporting BOM from Inventor 2022

### ISSUE THREAD

**Issue by gokcemay** [RespiraWorks/Ventilator#1149]
There are 67 parts in Ventilator. We can get XLSX files of Bill of Material (BOM) from Inventor. Attached is a [CSV file of a BOM with all parts](https://github.com/RespiraWorks/Ventilator/files/7045835/BOM.ventilator.csv) . There is an API for BOM generation and export. 

**What is required**
There should be a way to automate generating BOMs for all subassemblies. So that data generated can be used to generate web pages or request forms. 

**Subtasks:**
* [ ] Check if we can use API
* [ ] Determine how to use CSV files.

**How do you know it has to be done**
Wiki and parts list have to be generated by hand. Automating it will help and reduce workload.

Link to requirements or risk analysis if applicable.

**Starting points**
There is an API of Inventor below are two help pages.
BOM functions with iLogic: https://help.autodesk.com/view/INVNTOR/2022/ENU/?guid=GUID-5BEAA369-CFC0-482B-B01E-76914AAA750C
BOM API functions: https://help.autodesk.com/view/INVNTOR/2022/ENU/?guid=GUID-445993C4-420A-4F54-9E8A-26AE86546706

BOM Apps in Autodesk app store: https://apps.autodesk.com/INVNTOR/en/List/Search?isAppSearch=True&searchboxstore=INVNTOR&facet=&collection=&sort=&query=bom

**Don't forget**
- [x] Put the issue in a milestone
- [x] Assign it to one of the projects
- [x] Add appropriate labels
- [x] Mention dependent/blocked issues if any

**Comment by gokcemay** [comment]
There is another issue 1011 so closing this one.
