### ISSUE TITLE
Implement HAL for (analog) dP sensor on Rev1 interim board

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#1153]
**What is required**
We need to implement HAL and other sensor code for the additional dP sensor on the interim board.

**Subtasks:**
* [ ] Some HAL stuff
* [x] some Sensor abstrction stuff
* [ ] possibly some venturi stuff?

**How do you know it has to be done**
We need the the 3rd venturi working for closed loop oxygen control to work. We have proof of concept code for oxygen control in [this](https://github.com/RespiraWorks/Ventilator/tree/inceptionev/add_fio2_control) and [this](https://github.com/RespiraWorks/Ventilator/tree/inceptionev/experimental_nested_flow-pressure_control) branches (and possibly also [this](https://github.com/RespiraWorks/Ventilator/tree/inceptionev/experimental_interim_fio2_control)), but proper testing and merging is blocked by lack of 3rd flow sensor.  We want that code merged ASAP so that India team is not tempted to branch off of some experimental code for additional functionality.

**Starting points**
You may follow the example of how the on-board dP sensors (and venturi) are implemented. Good place to start pulling on the spaghetti is `sensors.h` and `sensors.cpp`. For pin numbers or whatever else is needed:
[Interim board repo](https://github.com/inceptionev/VentilatorRev1InterimDaughtercard) - ICD is linked from there too

**Don't forget**
- [x] Put the issue in a milestone
- [x] Assign it to one of the projects
- [x] Add appropriate labels
- [x] Mention dependent/blocked issues if any
