### ISSUE TITLE
Debug interface facilities for calibration storage

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#1154]
**What is required**

There should be a way to get and set calibration curve arrays via the debug interface. This will likely require the creation of a new `Debug::Variable` type.

A calibration curve is some N-sized array that could be used for either 
* sensor calibration, or
* actuator linearization

We may decide by convention to set the value of N to some constant - a good starting point can be 10, which is what we have used for  pinch valve calibration.

**Subtasks:**
* [ ] debug variable type for N-sized array
* [ ] debug interface (c++) commands for retrieving or manipulating the contents 
* [ ] debug interface client (Python) facilities
* [ ] replace pinch exiting hard-coded pinch valve calibration with this

**How do you know it has to be done**
We may soon have:
* multiple types of differential pressure sensors
* multiple versions of the venturi that may behave differently
* other types of pressure, oxygen or temperature sensors
* multiple types of valves

We also want to fully document our system configuration in test metadata.
Current debug variable facilities are inadequate for this, because we'd end up with dozens of individual variables.
The following tickets depend on and may be blocked by lack of this feature:
* #170 
* #838
* #857 
* #870 

**Starting points**
Current debug variable implementations are all limited to 32-bit types, but the base class is abstract enough.

It would probably be helpful to have some generated comms protocol in place that would not require all kinds of byte-by-byte hard-coding. There is a ticket (#1073) for this.

**Don't forget**
- [x] Put the issue in a milestone
- [x] Assign it to one of the projects
- [x] Add appropriate labels
- [x] Mention dependent/blocked issues if any
