### ISSUE TITLE
Update 1 to the enclosure documentation pages

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#1161]
**What has to be done**
All the markdown pages should be updated for the new tray(s) and enclosure assemblies to reference and link:
* new inventor files
* new renderings
* new drawings
* new parts

**What this is NOT**
We do not need detailed assembly instructions. This will be done after we get to build a few of these and can confim how it is done, and that will be capctured ticket .... TODO

**Subtasks:**
* [ ] Add subtasks or sections of content if applicable
* [ ] Identify documentation that should be updated upon completion

**How do you know it has to be done**
Link any documents, Slack threads, quote personal communication, reference your personal domain expertise etc. explaining why you think this should be done.

Link to requirements or risk analysis if applicable.

**Starting points**
Dependencies: #1160 #1099

**Don't forget**
- [ ] Put the issue in a milestone
- [ ] Assign it to one of the projects
- [ ] Add appropriate labels
- [ ] Mention dependent/blocked issues if any

**Comment by martukas** [comment]
Blocked #1099

**Comment by martukas** [comment]
Blocked by #1160
