### ISSUE TITLE
Hook up Pressure Assist mode to GUI

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#1178]
**What is required**
Implement the GUI part of Pressure Assist mode

**Subtasks:**
* [ ] Add an item in the mode selection, implement selection handler to give the command to the controller to switch the mode.
* [ ] Support the mode-specific set of parameters that the operator is able to set from GUI.

**How do you know it has to be done**
Pressure assist is a very important mode that could be used for patient treatment.
And implementing just the controller code is not enough - we need GUI part to work with it.

**Starting points**
Should be similar to how Pressure Control works.

**Don't forget**
- [ ] Put the issue in a milestone
- [ ] Assign it to one of the projects
- [ ] Add appropriate labels
- [ ] Mention dependent/blocked issues if any
