### ISSUE TITLE
Selection: oxygen check valve

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#1197]
**What has to be done**
Must select a check valve for the oxygen inlet.

**How do you know it has to be done**
This is to ensure one-way flow of oxygen from supply to the ventilator. It is probably quite unlikely that the blower system would generate enough pressure to actually cause back-flow into the oxygen system, particularly because this would likely A) pop the overpressure relief valve or B) have to go past the regulator. But, well, all of this should be looked into...

**TODO:** Link to requirements or risk analysis if applicable.

**Starting points**

As of v0.3, we are using this: https://www.mcmaster.com/7768K22/ right on the inlet.

Related to #646

**Don't forget**
- [ ] Put the issue in a milestone
- [ ] Assign it to one of the projects
- [ ] Add appropriate labels
- [ ] Mention dependent/blocked issues if any

**Comment by martukas** [comment]
Could be this?
https://www.mcmaster.com/47155K76/

Not sure on the pressure ratings.
