### ISSUE TITLE
Refine venturi design using computational models

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#1199]
**What has to be done**
Describe what has to be done, ideally in declarative form - what does success look like.

**Subtasks:**
* [ ] Add subtasks or sections of content if applicable
* [ ] Identify documentation that should be updated upon completion

**How do you know it has to be done**
Link any documents, Slack threads, quote personal communication, reference your personal domain expertise etc. explaining why you think this should be done.

Link to requirements or risk analysis if applicable.

**Starting points**
Where might one start with solving this problem? Point to any relevant files or websites. Even if you have but a vague idea, please share. Perhaps something has prevented you or blocked you from solving the problem already?

**Don't forget**
- [ ] Put the issue in a milestone
- [ ] Assign it to one of the projects
- [ ] Add appropriate labels
- [ ] Mention dependent/blocked issues if any

**Comment by martukas** [comment]
Previous work on this question was done in #705

Other related tickets:
#631 
#1122 
#636

**Comment by martukas** [comment]
Data files should be dumped on [Google drive](https://drive.google.com/drive/folders/1xd75hNHfbpOHuXmCEwh7YJWIuifTBUpx?usp=sharing)

**Comment by yusufcance** [comment]
We did not want to change anything with the outer design because important design requirements were related with inside. To overcome with high speed and low pressure in venturi side, we operated part wider. The reason we did not make exact circle is to send more stable air for sensor to analyze.
	After creating new model, we put it to the parametric analysis to gather different result in different inlet conditions.
	Result on models are as fallows with less eddies, turbulence, and less difference between inlet and outlet by side of speed and pressure.

**Comment by yusufcance** [comment]
![image](https://user-images.githubusercontent.com/99762127/158033526-c053d6f3-3717-4517-8694-4daa312a2056.png)
![image](https://user-images.githubusercontent.com/99762127/158033529-725a5e68-9e32-4422-8f13-b1518643f298.png)
![image](https://user-images.githubusercontent.com/99762127/158033534-6ec59f72-753a-4846-9253-a9d732938a46.png)

**Comment by yusufcance** [comment]
After creating new model, we put it to the parametric analysis to gather different result in different inlet conditions.
	Result on models are as fallows with less eddies, turbulence, and less difference between inlet and outlet by side of speed and pressure.

**Comment by yusufcance** [comment]
![image](https://user-images.githubusercontent.com/99762127/158033561-4b3df815-2b67-4095-8d80-4582f07e6604.png)
![image](https://user-images.githubusercontent.com/99762127/158033564-bd5227b2-c955-4ad7-90aa-224c027503db.png)

**Comment by yusufcance** [comment]
After all of these necessary informations and related datas we got from ANSYS, we would like to prepare plot which consists data of Pressure Difference on Sensors-mass Flow Rate on small region of tube. This analysis shows us we improved design by making a few changes inside of tube. This helps us to get close values im real-life tests.
![image](https://user-images.githubusercontent.com/99762127/158033848-f091d326-2772-4d70-8204-f53051751234.png)

**Comment by inceptionev** [comment]
Results from the venturi comparison with the original design.  Data is at this link: https://docs.google.com/spreadsheets/d/1CylfLKrE64rkY6gbZZj0AzY_0tv3djxfM-mScOxUXCw/edit?usp=sharing

![Turkey Team Modified Venturi Flow Characterization (4)](https://user-images.githubusercontent.com/8660661/175128686-faac32e3-1a9f-4894-b560-bc1efabad8df.png)

- The modified design produces less restriction of the flow, so the maximum flow is higher when the blower is turned up to its highest setting (9V for this setup)
- The sensitivity of the modified design is lower than the original, but neither get close to the full range of the 4kpa (40cmH2O) range of the dP sensor used in the ventilator design, and thus resolution is sacrificed, while also imparting a high pressure drop to the supply path of the ventilator
- This indicates to me that we should consider a lower-pressure dP sensor and a lower sensitivity venturi design to both reduce pressure drop and increase resolution.

**Comment by inceptionev** [comment]
Here is a plot summarizing what performance goals we want for the venturi:

![image](https://user-images.githubusercontent.com/8660661/175129148-dab718ca-5a70-4606-8a79-d955f1add0bd.png)

**Comment by yusufcance** [comment]
Real-time value helped us to analyze our values in a more realistic way which can be easily compared with the computational value. As you can see from the graph upward, the value we got from the new design has approach the expected value when the inlet flow increases. But main target is to approach the curve as much as we can. It requires different modeling techniques to understand the outcome. Understanging of the flow here is the key factor because to analyze flow you have to understand the flow path, affects which are created by flow also the understanding of the venturi principle. To claim expected curve, we have used 5 different models and put them the ANSYS Fluent to see how flow get affected with different modeling techniques.

**Comment by yusufcance** [comment]
1)	Slot Venturi Zone with Regular Outlet Pipe
 
![image](https://user-images.githubusercontent.com/99762127/183514982-1186e2ed-e8fd-4785-b261-8b6a06e3f119.png)
![image](https://user-images.githubusercontent.com/99762127/183515042-a38c8e28-ff3b-4ce2-8032-4977830f3011.png)

**Comment by yusufcance** [comment]
2)	Round-Small Venturi, Half-Regular Inlet and Regular Outlet
![image](https://user-images.githubusercontent.com/99762127/183515125-3f63a879-acea-473b-b91d-595c80b3eac5.png)
![image](https://user-images.githubusercontent.com/99762127/183515176-69465180-600f-427c-a331-98d56fe70534.png)

**Comment by yusufcance** [comment]
3)	Smaller Venturi, Fully Regular Pipe
![image](https://user-images.githubusercontent.com/99762127/183515285-d36b8a43-e3d7-40f7-8c70-86486e393088.png)
![image](https://user-images.githubusercontent.com/99762127/183515306-4bd9c3ea-f0bf-4a5e-8956-2f73b891fe68.png)

**Comment by yusufcance** [comment]
4)	Smooth Transiton
![image](https://user-images.githubusercontent.com/99762127/183515365-1ce65263-6ff1-48c3-9fdb-9aa36ff218b1.png)
![image](https://user-images.githubusercontent.com/99762127/183515396-dc8a07c2-a185-4dfd-b91e-c65d93dd7cc5.png)

**Comment by yusufcance** [comment]
5)	Modified Smooth Transition
![image](https://user-images.githubusercontent.com/99762127/183515457-9e7b85f6-5f40-4544-b5a2-a0f0b593e0a8.png)
![image](https://user-images.githubusercontent.com/99762127/183515495-6965a8bc-6210-430f-bada-3f84301f31d1.png)

**Comment by yusufcance** [comment]
Those are 5 different inner design and and flow analysis result. We gather all of the data to create parametric results. We had 2 real-time data, base and first modified design, which are not sufficient to create fully accurate parametrization. But with 5 new different data which are created in order will be very helpful and useful to create other options. Our main expectation is to get results from fifth design which may be more effective and accurate.
Theory of these design is to reduce rupture in the flow. By keeping more slope in transition we mostly provide that target. On the other side, we tried to keep clear sensor port inlets, that’s why there are difference in the first sensor pipe inlet between fourth anf fifth model. This ideology prevents air squeeze that helps us to get more accurate data. One other advantage is using smooth transition makes mathematical calculations easier. Because if you create more than one radius in the same curve, it will be harder on calculations. Analysing programs such as ANSYS create lesser need on mathematical calculations but to be certain it is also good to check mathematical side of the Venturi Principle.

**Comment by inceptionev** [comment]
Measured data from 3D printed #5: Modified Smooth Transition:

![image](https://user-images.githubusercontent.com/8660661/184924856-ea8095f9-e166-4925-ae01-84441101fb24.png)

**Comment by inceptionev** [comment]
possibly useful paper on venturis: https://sci-hub.se/10.1016/j.petrol.2011.08.008
