### ISSUE TITLE
Migrate PCB outputs to Google Drive

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#1205]
**What has to be done**
We should move all generated manufacturing files for the PCB into GoogleDrive. The repository should only track the original source files that determine the design.

**Subtasks:**
* [x] move rev1 stuff into some directory under v0.2-0.3 under [here](https://drive.google.com/drive/folders/1S_ymDEBAADw97bBJMZ8BxwIhojGhRJvo)
* [x] move new PCB output into a subdirectory under the v0.4 output folder also [here](https://drive.google.com/drive/folders/1S_ymDEBAADw97bBJMZ8BxwIhojGhRJvo)
* [x] make a branch where you change links in all readmes to point to those new locations, you can use something like https://tinyurl.com/app/ to make the google drive links less ugly
* [x] remove those files in the same branch

**How do you know it has to be done**
Repository bloat. Stuff is taking up too much space and eating into our bandwidth quota.

**Don't forget**
- [x] Put the issue in a milestone
- [x] Assign it to one of the projects
- [x] Add appropriate labels
- [x] Mention dependent/blocked issues if any
