### ISSUE TITLE
Update 3d printing guidelines.

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#1310]
**What has to be done**
3d printing guidelines are somewhat outdated. Could use improvement.

**Subtasks:**
* [ ] Siraya website now includes chitu config files, so we may not need as many bespoke ones in our repo
* [ ] Chitubox config files may also be moved to Google drive, as they are not strictly part of vent design
* [ ] Instructions should point contributors to google drive for sharing intermediate files, rather than encouraging them to commit to repo
* [ ] Could include list of tools and materials needed for SLA print processing - snips, blades, etc..

**How do you know it has to be done**
It's evident that the docs are outdated. I am trying to print again after a moderate break and am noticing these incongruencies.
