### ISSUE TITLE
Scripts for initial flashing of STM32 on v0.4

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#1312]
**What has to be done**
The `controller.sh` script should have a command for initial flashing of STlink to the STM32 processor on the v0.4 boards.

**Subtasks:**
* [ ] Add script for what can be done in Linux
* [ ] Save copies of additional files on Google drive, for steps that must be done in Windows
* [ ] Update documentation in repo
* [ ] Add additional tools needed to BOMs

**How do you know it has to be done**
Will need to be setting these up 

**Starting points**
There is a Google doc explaining how to do this in Windows.
