### ISSUE TITLE
Implement communications failure alarm in GUI

### ISSUE THREAD

**Issue by martukas** [RespiraWorks/Ventilator#837]
**What has to be done**
If the GUI does not receive data from the controller for a certain defined amount of time, then an alarm should sound.
Outstanding questions:
- [ ] how long of a delay before alarming?
- [ ] can alarm be silenced or reset? Discussed in #750 
- [ ] how loud must it be?

**How do you know it has to be done**
Because this is the main failure mode for our communications protocol.
**TODO:** Reference requirement or architecture document

**Code pointers**
* GUI alarm architecture is described [here](https://github.com/RespiraWorks/Ventilator/blob/master/software/design/GUI_alarm_subsystem.md)
* Other alarms have been implemented, such as `software/gui/src/patient_detached_alarm.h`
* **TODO:** how about the communications aspect?

**Other**
Sister issue for alarm on controller side is #817

**Don't forget**
- [ ] Put the issue in a milestone
- [ ] Assign it to one of the projects
- [ ] Add appropriate labels
- [ ] Mention dependent/blocked issues if any
